server:
  port : 8080
spring:
 h2:
   console:
    enabled: true
    path: /h2-console
 datasource:
   driverClassName: org.h2.Driver
   url: jdbc:h2:mem:springboot-interview
   username: sa
   password: